# Generated by Django 3.0.2 on 2020-03-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='univeersity',
            new_name='university',
        ),
    ]
